/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand.
 */

import type { ChromeEffect } from "../effect-types"
import type { DispatchChromeContext } from "../dispatch-context"
import { applyClearLogEffect } from "./effects/clear-log"
import { applyCloseTabEffect } from "./effects/close-tab"
import { applyExitPaneEffect } from "./effects/exit-pane"
import { applyGroupNewEffect } from "./effects/group-new"
import { applyNavigateCurrentTabEffect } from "./effects/navigate-current-tab"
import { applyOpenUrlNewTabEffect } from "./effects/open-url-new-tab"
import { applyOpenUrlNewWindowEffect } from "./effects/open-url-new-window"
import { applyReleaseNotesCurrentEffect } from "./effects/release-notes-current"
import { applyReleaseNotesListEffect } from "./effects/release-notes-list"
import { applyReleaseNotesVersionEffect } from "./effects/release-notes-version"
import { applyTabsMoveUrlEffect } from "./effects/tabs-move-url"
import { applyTabsNuEffect } from "./effects/tabs-nu"

export async function applyOne(
  ctx: DispatchChromeContext,
  e: ChromeEffect
): Promise<string[]> {
  switch (e.kind) {
    case "clear_log":
      return applyClearLogEffect(ctx, e)
    case "close_tab":
      return applyCloseTabEffect(ctx, e)
    case "exit_pane":
      return applyExitPaneEffect(ctx, e)
    case "group_new":
      return applyGroupNewEffect(ctx, e)
    case "navigate_current_tab":
      return applyNavigateCurrentTabEffect(ctx, e)
    case "open_url_new_tab":
      return applyOpenUrlNewTabEffect(ctx, e)
    case "open_url_new_window":
      return applyOpenUrlNewWindowEffect(ctx, e)
    case "release_notes_current":
      return applyReleaseNotesCurrentEffect(ctx, e)
    case "release_notes_list":
      return applyReleaseNotesListEffect(ctx, e)
    case "release_notes_version":
      return applyReleaseNotesVersionEffect(ctx, e)
    case "tabs_move_url":
      return applyTabsMoveUrlEffect(ctx, e)
    case "tabs_nu":
      return applyTabsNuEffect(ctx, e)
    default: {
      const _x: never = e
      return [`internal: unknown effect ${JSON.stringify(_x)}`]
    }
  }
}
