/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand.
 */

import type { ChromeEffect } from "../effect-types"
import type { DispatchChromeContext } from "../dispatch-context"
import { applyClearLogEffect } from "./effects/clear-log"
import { applyCloseTabEffect } from "./effects/close-tab"
import { applyDomListEffect } from "./effects/dom-list"
import { applyExitPaneEffect } from "./effects/exit-pane"
import { applyGroupNewEffect } from "./effects/group-new"
import { applyNavigateCurrentTabEffect } from "./effects/navigate-current-tab"
import { applyOpenUrlNewTabEffect } from "./effects/open-url-new-tab"
import { applyOpenUrlNewWindowEffect } from "./effects/open-url-new-window"
import { applyOpenWelcomePageEffect } from "./effects/open-welcome-page"
import { applySearchBookmarkEffect } from "./effects/search-bookmark"
import { applySearchHistoryEffect } from "./effects/search-history"
import { applySearchPageEffect } from "./effects/search-page"
import { applySessionNewEffect } from "./effects/session-new"
import { applySessionNextEffect } from "./effects/session-next"
import { applySessionPrevEffect } from "./effects/session-prev"
import { applyTabsMoveUrlEffect } from "./effects/tabs-move-url"
import { applyTabsNuEffect } from "./effects/tabs-nu"

export async function applyOne(
  ctx: DispatchChromeContext,
  e: ChromeEffect
): Promise<string[]> {
  switch (e.kind) {
    case "clear_log":
      return applyClearLogEffect(ctx, e)
    case "close_tab":
      return applyCloseTabEffect(ctx, e)
    case "dom_list":
      return applyDomListEffect(ctx, e)
    case "exit_pane":
      return applyExitPaneEffect(ctx, e)
    case "group_new":
      return applyGroupNewEffect(ctx, e)
    case "navigate_current_tab":
      return applyNavigateCurrentTabEffect(ctx, e)
    case "open_url_new_tab":
      return applyOpenUrlNewTabEffect(ctx, e)
    case "open_url_new_window":
      return applyOpenUrlNewWindowEffect(ctx, e)
    case "open_welcome_page":
      return applyOpenWelcomePageEffect(ctx, e)
    case "search_bookmark":
      return applySearchBookmarkEffect(ctx, e)
    case "search_history":
      return applySearchHistoryEffect(ctx, e)
    case "search_page":
      return applySearchPageEffect(ctx, e)
    case "session_new":
      return applySessionNewEffect(ctx, e)
    case "session_next":
      return applySessionNextEffect(ctx, e)
    case "session_prev":
      return applySessionPrevEffect(ctx, e)
    case "tabs_move_url":
      return applyTabsMoveUrlEffect(ctx, e)
    case "tabs_nu":
      return applyTabsNuEffect(ctx, e)
    default: {
      const _x: never = e
      return [`internal: unknown effect ${JSON.stringify(_x)}`]
    }
  }
}
