/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `npm run codegen`.
 */

export type SubcommandTailKind = "none" | "rest_http_url" | "rest"

export type CommandSubcommandBranch = {
  readonly head: string
  readonly trailingTokens: readonly string[]
  readonly tail: SubcommandTailKind
}

const EMPTY_BRANCHES: readonly CommandSubcommandBranch[] = []

/** canonicalName → declared second-token branches (from manifest `subcommands`). */
export const COMMAND_SUBCOMMAND_BRANCHES: Record<string, readonly CommandSubcommandBranch[]> = {
  "clear": [] as const,
  "close": [] as const,
  "dom": [
    { head: "-list", trailingTokens: ["--html","--react"] as const, tail: "rest" }
  ] as const,
  "exit": [] as const,
  "grep": [
    { head: "-list", trailingTokens: ["--none","--history","--bookmark","--page"] as const, tail: "rest" },
    { head: "--none", trailingTokens: [] as const, tail: "rest" },
    { head: "--history", trailingTokens: [] as const, tail: "rest" },
    { head: "--bookmark", trailingTokens: [] as const, tail: "rest" },
    { head: "--page", trailingTokens: [] as const, tail: "rest" }
  ] as const,
  "group": [] as const,
  "help": [] as const,
  "tabs": [
    { head: "-list", trailingTokens: ["-u"] as const, tail: "none" },
    { head: "-moveurl", trailingTokens: [] as const, tail: "rest_http_url" },
    { head: "-nowurl", trailingTokens: [] as const, tail: "none" }
  ] as const,
  "notes": [] as const,
  "split": [
    { head: "-col", trailingTokens: [] as const, tail: "none" },
    { head: "-row", trailingTokens: [] as const, tail: "none" }
  ] as const
}

export function getSubcommandBranches(canonicalName: string): readonly CommandSubcommandBranch[] {
  return COMMAND_SUBCOMMAND_BRANCHES[canonicalName] ?? EMPTY_BRANCHES
}

/** Tab completion: second token after `canonicalName ` (prefix filter, canonical spelling). */
export function listSecondTokenCandidatesByCommand(
  canonicalName: string,
  prefix: string
): string[] {
  const branches = getSubcommandBranches(canonicalName)
  if (branches.length === 0) return []
  const p = prefix.toLowerCase()
  return branches.map((b) => b.head).filter((h) => h.toLowerCase().startsWith(p))
}

/** Optional third fixed tokens after `secondTokenLower` (e.g. `-u` after `tabs -list`). */
export function listThirdTokenCandidates(
  canonicalName: string,
  secondTokenLower: string,
  prefix: string
): string[] {
  const branches = getSubcommandBranches(canonicalName)
  const br = branches.find((b) => b.head.toLowerCase() === secondTokenLower)
  if (!br?.trailingTokens?.length) return []
  const p = prefix.toLowerCase()
  return [...br.trailingTokens].filter((t) => t.toLowerCase().startsWith(p))
}

/** Enter with a single first token: restore `name ` when manifest declares subcommands. */
export function continuationPromptAfterLoneFirstToken(trimmedSingleToken: string): string | null {
  if (trimmedSingleToken.includes(" ")) return null
  const key = trimmedSingleToken.toLowerCase()
  const branches = getSubcommandBranches(key)
  if (!branches.length) return null
  return `${key} `
}

export function secondTokenCandidatesAfterLoneFirstToken(trimmedSingleToken: string): string[] {
  if (trimmedSingleToken.includes(" ")) return []
  const key = trimmedSingleToken.toLowerCase()
  return listSecondTokenCandidatesByCommand(key, "")
}

/** True when `token` is a manifest-declared second token (ASCII case-folding on `token`). */
export function isSecondToken(canonicalCmd: string, token: string): boolean {
  switch (canonicalCmd) {
    case "clear":
      return false
    case "close":
      return false
    case "dom": {
      const lower = token.toLowerCase()
      return lower === "-list"
    }
    case "exit":
      return false
    case "grep": {
      const lower = token.toLowerCase()
      return lower === "-list" || lower === "--none" || lower === "--history" || lower === "--bookmark" || lower === "--page"
    }
    case "group":
      return false
    case "help":
      return false
    case "tabs": {
      const lower = token.toLowerCase()
      return lower === "-list" || lower === "-moveurl" || lower === "-nowurl"
    }
    case "notes":
      return false
    case "split": {
      const lower = token.toLowerCase()
      return lower === "-col" || lower === "-row"
    }
    default:
      return false
  }
}

