/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `pnpm run codegen`.
 */
export const FALLBACK_COMPLETION_CANDIDATES: string[] = [
  "aboutbmxt",
  "clear",
  "close",
  "dom",
  "exit",
  "group",
  "help",
  "nav",
  "search",
  "session",
  "setting",
  "tabs",
  "translate"
]
