/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `npm run codegen`.
 */
export const FALLBACK_COMPLETION_CANDIDATES: string[] = [
  "?",
  "c",
  "clear",
  "close",
  "exit",
  "group",
  "help",
  "notes",
  "split-col",
  "split-row",
  "tabs"
]
