/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `npm run codegen`.
 */
export const FALLBACK_COMPLETION_CANDIDATES: string[] = [
  "clear",
  "close",
  "dom",
  "exit",
  "find",
  "group",
  "help",
  "nav",
  "notes",
  "split",
  "tabs"
]
