//! @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
//! 手で編集しない。コマンド追加は manifest を更新し `npm run codegen`。

use crate::cmd::{clear, close, exit, find, group, help_cmd, tabs, notes};
use crate::meta::Cmd;
use crate::model::DispatchJson;

type DispatchCmdFn = fn(&[String]) -> DispatchJson;

macro_rules! command_registry {
    ($($module:ident),* $(,)?) => {
        pub static COMMANDS: &[Cmd] = &[
            $($module::CMD),*
        ];

        pub static COMMAND_RUNNERS: &[(&'static str, DispatchCmdFn)] = &[
            $( ($module::CMD.name, $module::run as DispatchCmdFn) ),*
        ];
    };
}

command_registry! {
    clear,
    close,
    exit,
    find,
    group,
    help_cmd,
    tabs,
    notes,
}
