/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `npm run codegen`.
 */

export type ChromeEffect =
  | { kind: "clear_log" }
  | { kind: "close_tab"; tab_id: number }
  | { kind: "exit_pane" }
  | { kind: "find_group"; query: string }
  | { kind: "find_page_text"; query: string }
  | { kind: "find_page_title"; query: string }
  | { kind: "find_window_title"; query: string }
  | { kind: "group_new"; tab_ids: number[] }
  | { kind: "navigate_current_tab"; url: string }
  | { kind: "open_url_new_tab"; url: string }
  | { kind: "open_url_new_window"; url: string }
  | { kind: "release_notes_current" }
  | { kind: "release_notes_list" }
  | { kind: "release_notes_version"; version: string }
  | { kind: "tabs_move_url"; url: string }
  | { kind: "tabs_nu" }

export type DispatchBundle = {
  ty: "lines" | "effects"
  lines?: string[]
  effects?: ChromeEffect[]
}
