/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `pnpm run codegen`.
 */

export type ChromeEffect =
  | { dispatch_line: string; kind: "search_list" }
  | { flavor: string; kind: "dom_list"; pattern: string; pickerMode: string; showTag: string }
  | { kind: "clear_log" }
  | { kind: "close_tab"; tab_id: number }
  | { kind: "exit_pane" }
  | { kind: "group_new"; tab_ids: number[] }
  | { kind: "navigate_current_tab"; url: string }
  | { kind: "open_url_new_tab"; url: string }
  | { kind: "open_url_new_window"; url: string }
  | { kind: "open_welcome_page" }
  | { kind: "search_bookmark"; pattern: string }
  | { kind: "search_history"; pattern: string }
  | { kind: "search_page"; pattern: string }
  | { kind: "search_snapshot"; pattern: string }
  | { kind: "session_new"; name: string }
  | { kind: "session_next" }
  | { kind: "session_prev" }
  | { kind: "tabs_list"; show_url: string }
  | { kind: "tabs_move_url"; url: string }
  | { kind: "tabs_nu" }

export type DispatchMsg = { key: string; params?: Record<string, string> }

export type UiActionIR =
  | { kind: "show_help" }
  | { kind: "nav_arm" }
  | { kind: "nav_disarm" }
  | { kind: "open_plain_list"; line: string; list_id: string }
  | { kind: "close_picker"; slot: string }
  | { kind: "continuation_prompt"; prefix: string }
  | { kind: "session_list" }
  | { kind: "session_switch"; name: string }
  | { kind: "session_setting_name"; name: string }
  | { kind: "group_new_from_selection" }
  | { kind: "translate_on" }
  | { kind: "translate_off" }
  | { kind: "translate_setting"; pair: string }
  | { kind: "snapshot_save"; line: string }
  | { kind: "setting_list" }
  | { kind: "setting_exit_list" }
  | { kind: "tabs_exit_list" }
  | { kind: "tabs_setting"; mode: string }
  | { kind: "search_exit_list" }
  | { kind: "dom_exit_list" }
  | { kind: "dom_setting"; mode: string }
  | { kind: "browse"; line: string }
  | { kind: "picker_pass" }

export type DispatchBundle = {
  ty: "lines" | "effects" | "ui" | "msgs"
  lines?: string[]
  effects?: ChromeEffect[]
  action?: UiActionIR
  msgs?: DispatchMsg[]
  /** EN: Optional prompt restore after msgs (Rust prompt semantic SoT). */
  promptPrefix?: string
}
