/**
 * @generated by scripts/codegen/run.mjs — UiAction IR kinds (Rust bmxt-core/src/ir.rs).
 * Do not edit by hand; run `pnpm run codegen`.
 */

export type UiActionIR =
  | { kind: "show_help" }
  | { kind: "nav_arm" }
  | { kind: "nav_disarm" }
  | { kind: "nav_confirm_close"; target: string }
  | { kind: "open_plain_list"; line: string; list_id: string }
  | { kind: "close_picker"; slot: string }
  | { kind: "continuation_prompt"; prefix: string }
  | { kind: "session_list" }
  | { kind: "session_switch"; name: string }
  | { kind: "session_setting_name"; name: string }
  | { kind: "group_new_from_selection" }
  | { kind: "translate_on" }
  | { kind: "translate_off" }
  | { kind: "translate_setting"; pair: string }
  | { kind: "snapshot_save"; line: string }
  | { kind: "setting_list" }
  | { kind: "setting_exit_list" }
  | { kind: "tabs_exit_list" }
  | { kind: "tabs_setting"; mode: string }
  | { kind: "search_exit_list" }
  | { kind: "dom_exit_list" }
  | { kind: "dom_setting"; mode: string }
  | { kind: "browse"; line: string }
  | { kind: "picker_pass" }
