/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json uiActions[].
 * Do not edit by hand; run `pnpm run codegen`.
 */

export type UiActionIR =
  | { kind: "show_help" }
  | { kind: "nav_arm" }
  | { kind: "nav_disarm" }
  | { kind: "nav_confirm_close"; target: string }
  | { kind: "open_plain_list"; line: string; list_id: string }
  | { kind: "close_picker"; slot: string }
  | { kind: "continuation_prompt"; prefix: string }
  | { kind: "session_switch"; name: string }
  | { kind: "session_setting_name"; name: string }
  | { kind: "group_new_from_selection" }
  | { kind: "set_mode"; feature_id: string; mode: string }
  | { kind: "snapshot_save"; line: string }
  | { kind: "open_picker"; line: string; list_id: string; show_url: string }
  | { kind: "picker_pass" }
