pub static TABS_MAN: &[&str] = &[
  "NAME",
  "  tabs - tab list, URL jump, current URL (BMXt window / service worker)",
  "",
  "SYNOPSIS",
  "  tabs -l | --list              tab picker (titles; add -u for URLs under each title)",
  "  tabs -mu | --moveurl <url>   activate tab with that URL, or open a new tab if none match",
  "  tabs -nu | --nowurl          print the current tab URL (same target rules as back/forward)",
  "",
  "DESCRIPTION",
  "  tabs alone is invalid; use a subcommand.",
  "  -l opens the full-panel picker: all windows, group headers, tab titles.",
  "  With -l -u, each tab also shows its URL on the following line.",
  "  -mu accepts http(s) URLs only. Matching prefers an exact tab URL; otherwise first tab whose",
  "  URL starts with the given string; if none, opens a new tab.",
  "  In the BMXt prompt, after \"tabs -mu \" you can press Tab to cycle URLs of open http(s) tabs",
  "  (prefix-filtered by what you typed).",
  "",
  "KEYS (in picker, after tabs -l)",
  "  Opens with highlight on active tab of last-focused browser window.",
  "  j/ArrowDown next tab   k/ArrowUp previous",
  "  Shift+ArrowDown/ArrowUp: move highlight and mark a contiguous range with # (anchor fixed until plain move or marks cleared)",
  "  Tab toggles # mark on the highlighted tab (multi-select); same-window marks mirror Chrome's tab strip (tabs.highlight)",
  "  When any tab is marked: Space cycles [MOVE] -> [CLOSE] -> [GROUP] -> [NEW WINDOW] -> [MOVE] ...",
  "    [MOVE]: ArrowUp/ArrowDown choose destination row; Enter moves all # tabs before that tab",
  "    [CLOSE]: Enter closes all # tabs",
  "    [GROUP]: ArrowUp/ArrowDown pick target; first row is \"new group\" (set name/color); others are existing groups",
  "    [NEW WINDOW]: Enter moves all # tabs into one new browser window (order preserved by window then tab index)",
  "  / start filter (Esc ends filter; @ prefix filters URL substring)",
  "  Enter (when not in [MOVE]/[CLOSE]/[GROUP]/[NEW WINDOW] bulk mode) activates tab and focuses the page; picker stays open",
  "  Esc: if any # marks exist, clear all marks and stay in picker; else end filter, or end bulk mode, or exit picker",
];
