/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `npm run codegen`.
 */

import type { CmdMeta } from "../types"
import type { DispatchJson } from "../types"
import * as clear from "../cmd/clear"
import * as close from "../cmd/close"
import * as dom from "../cmd/dom"
import * as exit from "../cmd/exit"
import * as find from "../cmd/find"
import * as group from "../cmd/group"
import * as help_cmd from "../cmd/help_cmd"
import * as tabs from "../cmd/tabs"
import * as nav from "../cmd/nav"
import * as aboutbmxt from "../cmd/aboutbmxt"
import * as split from "../cmd/split"

export const COMMANDS: readonly CmdMeta[] = [
  clear.CMD,
  close.CMD,
  dom.CMD,
  exit.CMD,
  find.CMD,
  group.CMD,
  help_cmd.CMD,
  tabs.CMD,
  nav.CMD,
  aboutbmxt.CMD,
  split.CMD
]

export const COMMAND_RUNNERS: ReadonlyArray<{
  readonly name: string
  readonly run: (args: string[]) => DispatchJson
}> = [
  { name: clear.CMD.name, run: clear.run },
  { name: close.CMD.name, run: close.run },
  { name: dom.CMD.name, run: dom.run },
  { name: exit.CMD.name, run: exit.run },
  { name: find.CMD.name, run: find.run },
  { name: group.CMD.name, run: group.run },
  { name: help_cmd.CMD.name, run: help_cmd.run },
  { name: tabs.CMD.name, run: tabs.run },
  { name: nav.CMD.name, run: nav.run },
  { name: aboutbmxt.CMD.name, run: aboutbmxt.run },
  { name: split.CMD.name, run: split.run }
]

export function cmdByName(name: string): CmdMeta | undefined {
  return COMMANDS.find((c) => c.name === name)
}
