/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run `pnpm run codegen`.
 */

import type { CmdMeta } from "../types"

export const COMMANDS: readonly CmdMeta[] = [
  {
    name: "clear",
    aliases: [] as const,
    usagePrimary: "clear"
  },
  {
    name: "close",
    aliases: ["c"] as const,
    usagePrimary: "close <tabId>"
  },
  {
    name: "dom",
    aliases: [] as const,
    usagePrimary: "dom -list [--normal|--with] [--html|--react] [--tag] [<pattern>] | dom -exit -list | dom -setting -page-active"
  },
  {
    name: "exit",
    aliases: [] as const,
    usagePrimary: "exit"
  },
  {
    name: "search",
    aliases: [] as const,
    usagePrimary: "search -list [--all|--history|--bookmark|--page|--snapshot] [--unlimit] [<pattern>] | search -exit -list"
  },
  {
    name: "group",
    aliases: [] as const,
    usagePrimary: "group new"
  },
  {
    name: "help",
    aliases: ["?"] as const,
    usagePrimary: "help"
  },
  {
    name: "tabs",
    aliases: [] as const,
    usagePrimary: "tabs -list [-url] | tabs -exit -list | tabs -setting -page-active | tabs -moveurl <url> | tabs -nowurl"
  },
  {
    name: "nav",
    aliases: [] as const,
    usagePrimary: "nav -enter | nav -exit"
  },
  {
    name: "translate",
    aliases: [] as const,
    usagePrimary: "translate -on | translate -off | translate -setting"
  },
  {
    name: "aboutbmxt",
    aliases: [] as const,
    usagePrimary: "aboutbmxt"
  },
  {
    name: "session",
    aliases: [] as const,
    usagePrimary: "session -new [name] | session -list | session -switch [name] | session -next | session -prev | session -setting-name [name]"
  },
  {
    name: "snapshot",
    aliases: [] as const,
    usagePrimary: "snapshot -save [<tabId>]"
  },
  {
    name: "browse",
    aliases: [] as const,
    usagePrimary: "browse <list-command>"
  },
  {
    name: "setting",
    aliases: [] as const,
    usagePrimary: "setting -list | setting -exit -list"
  }
]

export function cmdByName(name: string): CmdMeta | undefined {
  return COMMANDS.find((c) => c.name === name)
}
