/**
 * 中立マニフェスト `manifest/bmxt-codegen.json` から Rust / TypeScript を生成する。
 * 単一出力: `npm run codegen`
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, "..", "..")
const manifestPath = join(root, "manifest", "bmxt-codegen.json")

function loadManifest() {
  const raw = readFileSync(manifestPath, "utf8")
  const m = JSON.parse(raw)
  if (m.schemaVersion !== 1) {
    throw new Error(`unsupported schemaVersion: ${m.schemaVersion}`)
  }
  if (!Array.isArray(m.commands) || !Array.isArray(m.effects)) {
    throw new Error("manifest must have commands[] and effects[]")
  }
  validateCommandsSubcommands(m.commands)
  return m
}

const TAIL_KINDS = new Set(["none", "rest_http_url", "rest"])

/** `commands[].subcommands` — second token heads, optional third fixed tokens, optional tail kind. */
function validateCommandsSubcommands(commands) {
  for (const c of commands) {
    if (c.subcommands === undefined) {
      throw new Error(
        `commands[].module=${c.module}: missing "subcommands" (use [] if no second-token family)`
      )
    }
    if (!Array.isArray(c.subcommands)) {
      throw new Error(`commands[].module=${c.module}: "subcommands" must be an array`)
    }
    const seen = new Set()
    for (const br of c.subcommands) {
      if (!br || typeof br !== "object") {
        throw new Error(`commands[].module=${c.module}: invalid subcommand branch`)
      }
      if (typeof br.head !== "string" || !br.head.startsWith("-")) {
        throw new Error(
          `commands[].module=${c.module}: each subcommand needs string "head" starting with "-" (got ${JSON.stringify(br?.head)})`
        )
      }
      const hl = br.head.toLowerCase()
      if (seen.has(hl)) {
        throw new Error(`commands[].module=${c.module}: duplicate subcommand head ${br.head}`)
      }
      seen.add(hl)
      if (br.trailingTokens !== undefined) {
        if (!Array.isArray(br.trailingTokens)) {
          throw new Error(`commands[].module=${c.module}: trailingTokens must be an array`)
        }
        for (const t of br.trailingTokens) {
          if (typeof t !== "string" || !t.startsWith("-")) {
            throw new Error(
              `commands[].module=${c.module}: trailingTokens entries must be strings starting with "-" (got ${JSON.stringify(t)})`
            )
          }
        }
      }
      const tail = br.tail ?? "none"
      if (!TAIL_KINDS.has(tail)) {
        throw new Error(
          `commands[].module=${c.module}: invalid tail ${JSON.stringify(tail)} (expected one of: none, rest_http_url, rest)`
        )
      }
    }
  }
}

function rustFieldType(t) {
  switch (t) {
    case "i32":
      return "i32"
    case "string":
      return "String"
    case "vec_i32":
      return "Vec<i32>"
    default:
      throw new Error(`unknown field type: ${t}`)
  }
}

function rustSampleValue(t) {
  switch (t) {
    case "i32":
      return "0"
    case "string":
      return "String::new()"
    case "vec_i32":
      return "vec![0]"
    default:
      throw new Error(`unknown field type: ${t}`)
  }
}

function emitRustEffectEnum(effects) {
  const lines = [
    "// @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json",
    "// Do not edit by hand.",
    "",
    "use serde::Serialize;",
    "",
    "#[derive(Debug, Serialize)]",
    '#[serde(tag = "kind", rename_all = "snake_case")]',
    "pub enum Effect {"
  ]
  for (const ef of effects) {
    if (ef.shape === "unit") {
      lines.push(`    ${ef.rustVariant},`)
    } else if (ef.shape === "record") {
      const fs = Object.entries(ef.fields)
      const inner = fs.map(([k, t]) => `        ${k}: ${rustFieldType(t)}`).join(",\n")
      lines.push(`    ${ef.rustVariant} {\n${inner},\n    },`)
    } else {
      throw new Error(`unknown shape: ${ef.shape}`)
    }
  }
  lines.push("}")
  return lines.join("\n") + "\n"
}

function emitRustEffectSamples(effects) {
  const arms = []
  for (const ef of effects) {
    if (ef.shape === "unit") {
      arms.push(`        Effect::${ef.rustVariant}`)
    } else {
      const fs = Object.entries(ef.fields)
      const inner = fs.map(([k, t]) => `${k}: ${rustSampleValue(t)}`).join(", ")
      arms.push(`        Effect::${ef.rustVariant} { ${inner} }`)
    }
  }
  return `// @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
// Do not edit by hand.

/// wasm32 ではリンクされない（ホストツール・ユニットテスト用）。
#[cfg(not(target_arch = "wasm32"))]
use super::effect_enum::Effect;

#[cfg(not(target_arch = "wasm32"))]
#[doc(hidden)]
pub fn effect_samples_for_ts_generation() -> Vec<Effect> {
    vec![
${arms.join(",\n")}
    ]
}

#[cfg(all(test, not(target_arch = "wasm32")))]
mod effect_ts_gen_tests {
    use super::*;

    #[test]
    fn effect_samples_have_unique_kind_strings() {
        let mut kinds = Vec::new();
        for e in effect_samples_for_ts_generation() {
            let v = serde_json::to_value(&e).expect("serialize");
            kinds.push(
                v.get("kind")
                    .and_then(|x| x.as_str())
                    .expect("kind present")
                    .to_string(),
            );
        }
        kinds.sort();
        let n = kinds.len();
        kinds.dedup();
        assert_eq!(
            kinds.len(),
            n,
            "duplicate kind in effect_samples_for_ts_generation"
        );
    }
}
`
}

function emitRustRegistryTable(commands) {
  const mods = commands.map((c) => c.module)
  const ids = `${mods.join(",\n    ")},`
  return `//! @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
//! 手で編集しない。コマンド追加は manifest を更新し \`npm run codegen\`。

use crate::cmd::{${mods.join(", ")}};
use crate::meta::Cmd;
use crate::model::DispatchJson;

type DispatchCmdFn = fn(&[String]) -> DispatchJson;

macro_rules! command_registry {
    ($($module:ident),* $(,)?) => {
        pub static COMMANDS: &[Cmd] = &[
            $($module::CMD),*
        ];

        pub static COMMAND_RUNNERS: &[(&'static str, DispatchCmdFn)] = &[
            $( ($module::CMD.name, $module::run as DispatchCmdFn) ),*
        ];
    };
}

command_registry! {
    ${ids}
}
`
}

function jsonValueToTsScalar(v) {
  if (v === null) return "null"
  if (typeof v === "boolean") return "boolean"
  if (typeof v === "number") return "number"
  if (typeof v === "string") return "string"
  if (Array.isArray(v)) {
    if (v.length === 0) return "number[]"
    return `${jsonValueToTsScalar(v[0])}[]`
  }
  if (typeof v === "object") return "Record<string, unknown>"
  return "unknown"
}

function buildEffectSampleObject(ef) {
  if (ef.shape === "unit") {
    return { kind: ef.kind }
  }
  const o = { kind: ef.kind }
  for (const [k, t] of Object.entries(ef.fields)) {
    if (t === "i32") o[k] = 0
    else if (t === "string") o[k] = ""
    else if (t === "vec_i32") o[k] = [0]
    else throw new Error(t)
  }
  return o
}

function emitTsEffectTypes(effects) {
  const members = []
  for (const ef of effects) {
    const sample = buildEffectSampleObject(ef)
    const sortedKeys = Object.keys(sample).sort()
    const parts = sortedKeys.map((k) => {
      const v = sample[k]
      if (k === "kind") {
        return `kind: ${JSON.stringify(v)}`
      }
      return `${k}: ${jsonValueToTsScalar(v)}`
    })
    members.push(`  | { ${parts.join("; ")} }`)
  }
  members.sort()
  const header = `/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run \`npm run codegen\`.
 */

export type ChromeEffect =
${members.join("\n")}

export type DispatchBundle = {
  ty: "lines" | "effects"
  lines?: string[]
  effects?: ChromeEffect[]
}
`
  return header.endsWith("\n") ? header : header + "\n"
}

function emitTsApplyDispatch(effects) {
  const lines = [
    "/**",
    " * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json",
    " * Do not edit by hand.",
    " */",
    "",
    'import type { ChromeEffect } from "../effect-types"',
    'import type { DispatchChromeContext } from "../dispatch-context"'
  ]
  const sorted = [...effects].sort((a, b) => a.tsHandlerFile.localeCompare(b.tsHandlerFile))
  for (const ef of sorted) {
    const modPath = `./effects/${ef.tsHandlerFile}`
    lines.push(
      `import { ${ef.tsHandlerExport} } from "${modPath}"`
    )
  }
  lines.push("")
  lines.push(
    "export async function applyOne(",
    "  ctx: DispatchChromeContext,",
    "  e: ChromeEffect",
    "): Promise<string[]> {"
  )
  lines.push("  switch (e.kind) {")
  for (const ef of [...effects].sort((a, b) => a.kind.localeCompare(b.kind))) {
    lines.push(`    case ${JSON.stringify(ef.kind)}:`)
    lines.push(`      return ${ef.tsHandlerExport}(ctx, e)`)
  }
  lines.push("    default: {")
  lines.push("      const _x: never = e")
  lines.push(
    '      return [`internal: unknown effect ${JSON.stringify(_x)}`]'
  )
  lines.push("    }")
  lines.push("  }")
  lines.push("}")
  lines.push("")
  return lines.join("\n")
}

function emitCompletionFallback(commands) {
  const set = new Set()
  for (const c of commands) {
    set.add(c.canonicalName)
    for (const a of c.aliases) {
      set.add(a)
    }
  }
  const tokens = [...set].sort()
  const arr = tokens.map((t) => `  ${JSON.stringify(t)}`).join(",\n")
  return `/**
 * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
 * Do not edit by hand; run \`npm run codegen\`.
 */
export const FALLBACK_COMPLETION_CANDIDATES: string[] = [
${arr}
]
`
}

function normalizeBranch(br) {
  return {
    head: br.head,
    trailingTokens: Array.isArray(br.trailingTokens) ? br.trailingTokens : [],
    tail: br.tail ?? "none"
  }
}

function emitTsCommandSubcommands(commands) {
  const lines = []
  lines.push("/**")
  lines.push(" * @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json")
  lines.push(" * Do not edit by hand; run `npm run codegen`.")
  lines.push(" */")
  lines.push("")
  lines.push('export type SubcommandTailKind = "none" | "rest_http_url" | "rest"')
  lines.push("")
  lines.push("export type CommandSubcommandBranch = {")
  lines.push("  readonly head: string")
  lines.push("  readonly trailingTokens: readonly string[]")
  lines.push("  readonly tail: SubcommandTailKind")
  lines.push("}")
  lines.push("")
  lines.push("const EMPTY_BRANCHES: readonly CommandSubcommandBranch[] = []")
  lines.push("")
  const recordParts = []
  for (const c of commands) {
    const branches = c.subcommands.map(normalizeBranch)
    const objLit = branches
      .map((b) => {
        const tt = JSON.stringify(b.trailingTokens)
        return `    { head: ${JSON.stringify(b.head)}, trailingTokens: ${tt} as const, tail: ${JSON.stringify(b.tail)} }`
      })
      .join(",\n")
    const value =
      branches.length === 0 ? "[] as const" : `[\n${objLit}\n  ] as const`
    recordParts.push(`  ${JSON.stringify(c.canonicalName)}: ${value}`)
  }
  lines.push("/** canonicalName → declared second-token branches (from manifest `subcommands`). */")
  lines.push("export const COMMAND_SUBCOMMAND_BRANCHES: Record<string, readonly CommandSubcommandBranch[]> = {")
  lines.push(recordParts.join(",\n"))
  lines.push("}")
  lines.push("")
  lines.push("export function getSubcommandBranches(canonicalName: string): readonly CommandSubcommandBranch[] {")
  lines.push("  return COMMAND_SUBCOMMAND_BRANCHES[canonicalName] ?? EMPTY_BRANCHES")
  lines.push("}")
  lines.push("")
  lines.push("/** Tab completion: second token after `canonicalName ` (prefix filter, canonical spelling). */")
  lines.push("export function listSecondTokenCandidatesByCommand(")
  lines.push("  canonicalName: string,")
  lines.push("  prefix: string")
  lines.push("): string[] {")
  lines.push("  const branches = getSubcommandBranches(canonicalName)")
  lines.push("  if (branches.length === 0) return []")
  lines.push("  const p = prefix.toLowerCase()")
  lines.push("  return branches.map((b) => b.head).filter((h) => h.toLowerCase().startsWith(p))")
  lines.push("}")
  lines.push("")
  lines.push("/** Optional third fixed tokens after `secondTokenLower` (e.g. `-u` after `tabs -list`). */")
  lines.push("export function listThirdTokenCandidates(")
  lines.push("  canonicalName: string,")
  lines.push("  secondTokenLower: string,")
  lines.push("  prefix: string")
  lines.push("): string[] {")
  lines.push("  const branches = getSubcommandBranches(canonicalName)")
  lines.push("  const br = branches.find((b) => b.head.toLowerCase() === secondTokenLower)")
  lines.push("  if (!br?.trailingTokens?.length) return []")
  lines.push("  const p = prefix.toLowerCase()")
  lines.push("  return [...br.trailingTokens].filter((t) => t.toLowerCase().startsWith(p))")
  lines.push("}")
  lines.push("")
  lines.push("/** Enter with a single first token: restore `name ` when manifest declares subcommands. */")
  lines.push("export function continuationPromptAfterLoneFirstToken(trimmedSingleToken: string): string | null {")
  lines.push("  if (trimmedSingleToken.includes(\" \")) return null")
  lines.push("  const key = trimmedSingleToken.toLowerCase()")
  lines.push("  const branches = getSubcommandBranches(key)")
  lines.push("  if (!branches.length) return null")
  lines.push("  return `${key} `")
  lines.push("}")
  lines.push("")
  lines.push("export function secondTokenCandidatesAfterLoneFirstToken(trimmedSingleToken: string): string[] {")
  lines.push("  if (trimmedSingleToken.includes(\" \")) return []")
  lines.push("  const key = trimmedSingleToken.toLowerCase()")
  lines.push("  return listSecondTokenCandidatesByCommand(key, \"\")")
  lines.push("}")
  lines.push("")
  return lines.join("\n") + "\n"
}

function emitRustCommandSubcommands(commands) {
  const arms = []
  for (const c of commands) {
    const heads = c.subcommands.map((b) => normalizeBranch(b).head.toLowerCase())
    if (heads.length === 0) {
      arms.push(`        "${c.canonicalName}" => false`)
      continue
    }
    const pat = heads.map((h) => JSON.stringify(h)).join(" | ")
    arms.push(`        "${c.canonicalName}" => {
            let lower = token.to_ascii_lowercase();
            matches!(lower.as_str(), ${pat})
        }`)
  }
  const matchBody = arms.join(",\n")
  return `// @generated by scripts/codegen/run.mjs from manifest/bmxt-codegen.json
// Do not edit by hand.

/// True when \`token\` is a manifest-declared **second** token for \`canonical_cmd\` (ASCII case-folding on \`token\`).
pub fn is_second_token(canonical_cmd: &str, token: &str) -> bool {
    match canonical_cmd {
${matchBody},
        _ => false,
    }
}
`
}

function emitGeneratedMod() {
  return `//! @generated — see scripts/codegen/run.mjs

pub mod command_subcommands;
mod effect_enum;
mod effect_samples;

pub use effect_enum::Effect;
`
}

function ensureDir(p) {
  if (!existsSync(p)) {
    mkdirSync(p, { recursive: true })
  }
}

function main() {
  const m = loadManifest()

  const genDir = join(root, "wasm", "bmxt-core", "src", "generated")
  ensureDir(genDir)

  writeFileSync(
    join(genDir, "effect_enum.rs"),
    emitRustEffectEnum(m.effects),
    "utf8"
  )
  writeFileSync(
    join(genDir, "effect_samples.rs"),
    emitRustEffectSamples(m.effects),
    "utf8"
  )
  writeFileSync(
    join(genDir, "command_subcommands.rs"),
    emitRustCommandSubcommands(m.commands),
    "utf8"
  )
  writeFileSync(join(genDir, "mod.rs"), emitGeneratedMod(), "utf8")

  writeFileSync(
    join(root, "wasm", "bmxt-core", "src", "registry", "table.rs"),
    emitRustRegistryTable(m.commands),
    "utf8"
  )

  const dispatchPath = join(
    root,
    "lib",
    "features",
    "dispatch",
    "handlers",
    "apply-dispatch.gen.ts"
  )
  writeFileSync(dispatchPath, emitTsApplyDispatch(m.effects), "utf8")

  writeFileSync(
    join(root, "lib", "features", "dispatch", "effect-types.ts"),
    emitTsEffectTypes(m.effects),
    "utf8"
  )

  writeFileSync(
    join(
      root,
      "lib",
      "features",
      "builtin-commands",
      "completion-fallback.ts"
    ),
    emitCompletionFallback(m.commands),
    "utf8"
  )

  writeFileSync(
    join(root, "lib", "features", "builtin-commands", "command-subcommands.gen.ts"),
    emitTsCommandSubcommands(m.commands),
    "utf8"
  )

  console.log(
    "codegen ok: Rust registry + generated/ (effects + command_subcommands), effect-types, apply-dispatch.gen, completion-fallback, command-subcommands.gen.ts"
  )
}

main()
